# Aliases
alias vim=nvim
alias vi=nvim
alias mn3="ssh mn3"
alias mn0="ssh mn0"

alias -s tex=vim
alias -s c=vim
alias -s go=vim
alias -s pdf=zathura

alias -g L='| less'
alias -g LL="2>&1 | less"
alias -g C='| wc -l'
alias -g NUL="> /dev/null 2>&1"
alias -g G='| egrep'

# Completion things

## Completion cache
zstyle ':completion:*' use-cache on
zstyle ':completion:*' cache-path ~/.zsh/cache

## Completion admit errors
zstyle ':completion:*' completer _complete _match _approximate
zstyle ':completion:*:match:*' original only
zstyle ':completion:*:approximate:*' max-errors 1 numeric

## Don't complete non existent commands
zstyle ':completion:*:functions' ignored-patterns '_*'


